version: "3.9"

services:
  mohist:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./data:/opt/mohist/data
      - ./output:/opt/mohist/output
